name: flutter_direct
description: Design System for Home Credit Indonesia Tippers App.
version: 0.0.8
author: dopefaceee, satriantorobimo & arlakay
homepage: https://github.com/fe-homecredit-id/flutter-direct

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
  - assets/female.png
 
  fonts:
    - family: Campton
      fonts:
        - asset: packages/flutter_direct/fonts/Campton-Book.otf
        - asset: packages/flutter_direct/fonts/Campton-Light.otf
        - asset: packages/flutter_direct/fonts/Campton-Medium.otf
        - asset: packages/flutter_direct/fonts/Campton-Bold.otf
    - family: Raleway
      fonts:
        - asset: packages/flutter_direct/fonts/Raleway-Regular.ttf
        - asset: packages/flutter_direct/fonts/Raleway-Light.ttf
        - asset: packages/flutter_direct/fonts/Raleway-Medium.ttf
        - asset: packages/flutter_direct/fonts/Raleway-Bold.ttf
    - family: PtSans
      fonts:
        - asset: packages/flutter_direct/fonts/PTSans-Regular.ttf
        - asset: packages/flutter_direct/fonts/PTSans-RegularItalic.ttf
        - asset: packages/flutter_direct/fonts/PTSans-Bold.ttf
        - asset: packages/flutter_direct/fonts/PTSans-BoldItalic.ttf


