name: flutter_direct
description: Design System for Home Credit Indonesia Tippers App.
version: 0.0.4
author: dopefaceee, satriantorobimo & arlakay
homepage: https://github.com/fe-homecredit-id/flutter-direct

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  carousel_slider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - packages/flutter_direct/imgs/image.png
  # To add assets to your package, add an assets section, like this:
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: packages/flutter_direct/fonts/HelveticaNeue.ttf
        - asset: packages/flutter_direct/fonts/HelveticaNeue-Italic.ttf
          style: italic
        - asset: packages/flutter_direct/fonts/HelveticaNeue-Medium.ttf
          weight: 500
        - asset: packages/flutter_direct/fonts/HelveticaNeue-Bold.ttf
          weight: 600
    - family: Campton
      fonts:
        - asset: packages/flutter_direct/fonts/Campton-Book.otf
        - asset: packages/flutter_direct/fonts/Campton-Light.otf
        - asset: packages/flutter_direct/fonts/Campton-Medium.otf
          weight: 500
        - asset: packages/flutter_direct/fonts/Campton-Bold.otf
          weight: 600
    - family: Raleway
      fonts:
        - asset: packages/flutter_direct/fonts/Raleway-Regular.ttf
        - asset: packages/flutter_direct/fonts/Raleway-Light.ttf
        - asset: packages/flutter_direct/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: packages/flutter_direct/fonts/Raleway-Bold.ttf
          weight: 600
    - family: PtSans
      fonts:
        - asset: packages/flutter_direct/fonts/PTSans-Regular.ttf
        - asset: packages/flutter_direct/fonts/PTSans-RegularItalic.ttf
        - asset: packages/flutter_direct/fonts/PTSans-Bold.ttf
          weight: 500
        - asset: packages/flutter_direct/fonts/PTSans-BoldItalic.ttf
          weight: 600


  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
